
BUILD 	= ../../build

all: filecomp linenoise

filecomp: filecomp.c filecomp.h 
	$(CC) -Wall -W -g -c -o $(BUILD)/filecomp.o filecomp.c

linenoise: linenoise.c linenoise.h
	$(CC) -Wall -W -g -c -o $(BUILD)/linenoise.o linenoise.c

